### PR TITLE
Update to 2.57

### PR DESCRIPTION
**Pull request by filipestevao**

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
Thanks, we probably don't need the .flatpak-builder folder though

**Comment by filipestevao** [comment]
Sorry, I did not understand. Do you want to have the .flatpak.builder folder back?

**Comment by Hofer-Julian** [comment]
Ah you deleted it.

Will check if the build works and then merge it

**Comment by Hofer-Julian** [comment]
Runs fine, thanks!

**Pull request merged**
